name: multi-java

on: [create, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Store Java 1.8 Home
      run: echo ::set-env name=JAVA_HOME_8::$JAVA_HOME 
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    - name: Store Java 11 Home
      run: echo ::set-env name=JAVA_HOME_11::$JAVA_HOME
    - name: check env
      run: |
        echo "Java 1.8: ${JAVA_HOME_8}"
        echo "Java 11: ${JAVA_HOME_11}"
    - name: output
      run: |
        ls -al ~/.m2
        cat ~/.m2/settings.xml
        cat ~/.m2/toolchains.xml
